# Generated by Django 5.0.6 on 2024-06-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='converted_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
