# Generated by Django 5.0.6 on 2024-06-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_mediafile_uploaded_at_mediafile_output_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='converted_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='output_format',
            field=models.CharField(default='mp3', max_length=10),
        ),
    ]
